- name: Deploy web application using Nginx
  hosts: webservers
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Update apt cache and install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy website files to document root
      copy:
        src: ./site/
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'

    - name: Apply Nginx configuration template
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/{{ app_name }}
      notify: Restart Nginx

    - name: Enable Nginx site
      file:
        src: /etc/nginx/sites-available/{{ app_name }}
        dest: /etc/nginx/sites-enabled/{{ app_name }}
        state: link
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
